//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House.Of.Arbitration.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("House.Of.Arbitration.Localization.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ADD CATEGORY].
        /// </summary>
        public static string ADD_CATEGORY {
            get {
                return ResourceManager.GetString("ADD_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ADD COMPETITION].
        /// </summary>
        public static string ADD_COMPETITION {
            get {
                return ResourceManager.GetString("ADD_COMPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [APPLICATION NAME].
        /// </summary>
        public static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [CATEGORIES LIST].
        /// </summary>
        public static string CATEGORY_LIST {
            get {
                return ResourceManager.GetString("CATEGORY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [CLOSE].
        /// </summary>
        public static string CLOSE_ACTION {
            get {
                return ResourceManager.GetString("CLOSE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [COMPETITION DATE].
        /// </summary>
        public static string COMPETITION_DATE {
            get {
                return ResourceManager.GetString("COMPETITION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [COMPETITION&apos;S LIST].
        /// </summary>
        public static string COMPETITION_LIST {
            get {
                return ResourceManager.GetString("COMPETITION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [COMPETITION NAME].
        /// </summary>
        public static string COMPETITION_NAME {
            get {
                return ResourceManager.GetString("COMPETITION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [COMPETITION SETTINGS].
        /// </summary>
        public static string COMPETITION_SETTINGS {
            get {
                return ResourceManager.GetString("COMPETITION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM AGE CADETS].
        /// </summary>
        public static string ENUM_AGE_CADETS {
            get {
                return ResourceManager.GetString("ENUM_AGE_CADETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM AGE ESPOIRS].
        /// </summary>
        public static string ENUM_AGE_ESPOIRS {
            get {
                return ResourceManager.GetString("ENUM_AGE_ESPOIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM AGE JUNIORS].
        /// </summary>
        public static string ENUM_AGE_JUNIORS {
            get {
                return ResourceManager.GetString("ENUM_AGE_JUNIORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM AGE NONE].
        /// </summary>
        public static string ENUM_AGE_NONE {
            get {
                return ResourceManager.GetString("ENUM_AGE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM AGE SENIORS].
        /// </summary>
        public static string ENUM_AGE_SENIORS {
            get {
                return ResourceManager.GetString("ENUM_AGE_SENIORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM AGE VETERANS].
        /// </summary>
        public static string ENUM_AGE_VETERANS {
            get {
                return ResourceManager.GetString("ENUM_AGE_VETERANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM CATEGORY NONE].
        /// </summary>
        public static string ENUM_CATEGORY_NONE {
            get {
                return ResourceManager.GetString("ENUM_CATEGORY_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM CATEGORY SANDA].
        /// </summary>
        public static string ENUM_CATEGORY_SANDA {
            get {
                return ResourceManager.GetString("ENUM_CATEGORY_SANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM CATEGORY SANDA LIGHT].
        /// </summary>
        public static string ENUM_CATEGORY_SANDALIGHT {
            get {
                return ResourceManager.GetString("ENUM_CATEGORY_SANDALIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM CATEGORY TAOLU].
        /// </summary>
        public static string ENUM_CATEGORY_TAOLU {
            get {
                return ResourceManager.GetString("ENUM_CATEGORY_TAOLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM GENRE MEN].
        /// </summary>
        public static string ENUM_GENRE_MEN {
            get {
                return ResourceManager.GetString("ENUM_GENRE_MEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM GENRE NONE].
        /// </summary>
        public static string ENUM_GENRE_NONE {
            get {
                return ResourceManager.GetString("ENUM_GENRE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM GENRE WOMEN].
        /// </summary>
        public static string ENUM_GENRE_WOMEN {
            get {
                return ResourceManager.GetString("ENUM_GENRE_WOMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM ROUND ELIMINATION].
        /// </summary>
        public static string ENUM_ROUND_ELIMINATION {
            get {
                return ResourceManager.GetString("ENUM_ROUND_ELIMINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM ROUND GROUP].
        /// </summary>
        public static string ENUM_ROUND_GROUP {
            get {
                return ResourceManager.GetString("ENUM_ROUND_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ENUM ROUND NONE].
        /// </summary>
        public static string ENUM_ROUND_NONE {
            get {
                return ResourceManager.GetString("ENUM_ROUND_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [GENRE].
        /// </summary>
        public static string GENRE {
            get {
                return ResourceManager.GetString("GENRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [MASTER].
        /// </summary>
        public static string MASTER {
            get {
                return ResourceManager.GetString("MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [NAME REQUIRED].
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [NEW CATEGORY].
        /// </summary>
        public static string NEW_CATEGORY {
            get {
                return ResourceManager.GetString("NEW_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [NEXT].
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [NO COMPETITION].
        /// </summary>
        public static string NO_COMPETITION {
            get {
                return ResourceManager.GetString("NO_COMPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [OLD].
        /// </summary>
        public static string OLD {
            get {
                return ResourceManager.GetString("OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [PLACEHOLDER COMPETITION NAME].
        /// </summary>
        public static string PLACEHOLDER_COMPETITION_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_COMPETITION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [PREVIOUS].
        /// </summary>
        public static string PREVIOUS {
            get {
                return ResourceManager.GetString("PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ROUND TYPE].
        /// </summary>
        public static string ROUND_TYPE {
            get {
                return ResourceManager.GetString("ROUND_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [SLAVE].
        /// </summary>
        public static string SLAVE {
            get {
                return ResourceManager.GetString("SLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [START COMPETITION].
        /// </summary>
        public static string START_COMPETITION {
            get {
                return ResourceManager.GetString("START_COMPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [STYLE].
        /// </summary>
        public static string STYLE {
            get {
                return ResourceManager.GetString("STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [VALIDATE].
        /// </summary>
        public static string VALIDATE_ACTION {
            get {
                return ResourceManager.GetString("VALIDATE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [WEIGHT MAX].
        /// </summary>
        public static string WEIGHT_MAX {
            get {
                return ResourceManager.GetString("WEIGHT_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [WEIGHT MIN].
        /// </summary>
        public static string WEIGHT_MIN {
            get {
                return ResourceManager.GetString("WEIGHT_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [WEIGHT UNIT].
        /// </summary>
        public static string WEIGHT_UNIT {
            get {
                return ResourceManager.GetString("WEIGHT_UNIT", resourceCulture);
            }
        }
    }
}
