<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <TargetFrameworks>$(NetVersion)-android</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);$(NetVersion)-$(WindowsVersion)</TargetFrameworks>

    <!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>House.Of.Arbitration.App</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>

		<!-- Display name -->
		<ApplicationTitle>House.Of.Arbitration.App</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.house.of.arbitration.app</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">$(AndroidTarget)</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">$(WindowsTarget)</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">$(WindowsTarget)</TargetPlatformMinVersion>
  </PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Images\Flags\ad.png" />
	  <None Remove="Resources\Images\Flags\ae.png" />
	  <None Remove="Resources\Images\Flags\af.png" />
	  <None Remove="Resources\Images\Flags\ag.png" />
	  <None Remove="Resources\Images\Flags\al.png" />
	  <None Remove="Resources\Images\Flags\am.png" />
	  <None Remove="Resources\Images\Flags\ao.png" />
	  <None Remove="Resources\Images\Flags\ar.png" />
	  <None Remove="Resources\Images\Flags\at.png" />
	  <None Remove="Resources\Images\Flags\au.png" />
	  <None Remove="Resources\Images\Flags\az.png" />
	  <None Remove="Resources\Images\Flags\ba.png" />
	  <None Remove="Resources\Images\Flags\bb.png" />
	  <None Remove="Resources\Images\Flags\bd.png" />
	  <None Remove="Resources\Images\Flags\be.png" />
	  <None Remove="Resources\Images\Flags\bf.png" />
	  <None Remove="Resources\Images\Flags\bg.png" />
	  <None Remove="Resources\Images\Flags\bh.png" />
	  <None Remove="Resources\Images\Flags\bi.png" />
	  <None Remove="Resources\Images\Flags\bj.png" />
	  <None Remove="Resources\Images\Flags\bn.png" />
	  <None Remove="Resources\Images\Flags\bo.png" />
	  <None Remove="Resources\Images\Flags\br.png" />
	  <None Remove="Resources\Images\Flags\bs.png" />
	  <None Remove="Resources\Images\Flags\bt.png" />
	  <None Remove="Resources\Images\Flags\bw.png" />
	  <None Remove="Resources\Images\Flags\by.png" />
	  <None Remove="Resources\Images\Flags\bz.png" />
	  <None Remove="Resources\Images\Flags\ca.png" />
	  <None Remove="Resources\Images\Flags\cd.png" />
	  <None Remove="Resources\Images\Flags\cf.png" />
	  <None Remove="Resources\Images\Flags\cg.png" />
	  <None Remove="Resources\Images\Flags\ch.png" />
	  <None Remove="Resources\Images\Flags\ci.png" />
	  <None Remove="Resources\Images\Flags\cl.png" />
	  <None Remove="Resources\Images\Flags\cm.png" />
	  <None Remove="Resources\Images\Flags\cn.png" />
	  <None Remove="Resources\Images\Flags\co.png" />
	  <None Remove="Resources\Images\Flags\cr.png" />
	  <None Remove="Resources\Images\Flags\cu.png" />
	  <None Remove="Resources\Images\Flags\cv.png" />
	  <None Remove="Resources\Images\Flags\cy.png" />
	  <None Remove="Resources\Images\Flags\cz.png" />
	  <None Remove="Resources\Images\Flags\de.png" />
	  <None Remove="Resources\Images\Flags\dj.png" />
	  <None Remove="Resources\Images\Flags\dk.png" />
	  <None Remove="Resources\Images\Flags\dm.png" />
	  <None Remove="Resources\Images\Flags\do.png" />
	  <None Remove="Resources\Images\Flags\dz.png" />
	  <None Remove="Resources\Images\Flags\ec.png" />
	  <None Remove="Resources\Images\Flags\ee.png" />
	  <None Remove="Resources\Images\Flags\eg.png" />
	  <None Remove="Resources\Images\Flags\er.png" />
	  <None Remove="Resources\Images\Flags\es.png" />
	  <None Remove="Resources\Images\Flags\et.png" />
	  <None Remove="Resources\Images\Flags\fi.png" />
	  <None Remove="Resources\Images\Flags\fj.png" />
	  <None Remove="Resources\Images\Flags\fm.png" />
	  <None Remove="Resources\Images\Flags\fr.png" />
	  <None Remove="Resources\Images\Flags\ga.png" />
	  <None Remove="Resources\Images\Flags\gb.png" />
	  <None Remove="Resources\Images\Flags\gd.png" />
	  <None Remove="Resources\Images\Flags\ge.png" />
	  <None Remove="Resources\Images\Flags\gh.png" />
	  <None Remove="Resources\Images\Flags\gm.png" />
	  <None Remove="Resources\Images\Flags\gn.png" />
	  <None Remove="Resources\Images\Flags\gq.png" />
	  <None Remove="Resources\Images\Flags\gr.png" />
	  <None Remove="Resources\Images\Flags\gt.png" />
	  <None Remove="Resources\Images\Flags\gw.png" />
	  <None Remove="Resources\Images\Flags\gy.png" />
	  <None Remove="Resources\Images\Flags\hn.png" />
	  <None Remove="Resources\Images\Flags\hr.png" />
	  <None Remove="Resources\Images\Flags\ht.png" />
	  <None Remove="Resources\Images\Flags\hu.png" />
	  <None Remove="Resources\Images\Flags\id.png" />
	  <None Remove="Resources\Images\Flags\ie.png" />
	  <None Remove="Resources\Images\Flags\il.png" />
	  <None Remove="Resources\Images\Flags\in.png" />
	  <None Remove="Resources\Images\Flags\iq.png" />
	  <None Remove="Resources\Images\Flags\ir.png" />
	  <None Remove="Resources\Images\Flags\is.png" />
	  <None Remove="Resources\Images\Flags\it.png" />
	  <None Remove="Resources\Images\Flags\jm.png" />
	  <None Remove="Resources\Images\Flags\jo.png" />
	  <None Remove="Resources\Images\Flags\jp.png" />
	  <None Remove="Resources\Images\Flags\ke.png" />
	  <None Remove="Resources\Images\Flags\kg.png" />
	  <None Remove="Resources\Images\Flags\kh.png" />
	  <None Remove="Resources\Images\Flags\ki.png" />
	  <None Remove="Resources\Images\Flags\km.png" />
	  <None Remove="Resources\Images\Flags\kn.png" />
	  <None Remove="Resources\Images\Flags\kp.png" />
	  <None Remove="Resources\Images\Flags\kr.png" />
	  <None Remove="Resources\Images\Flags\kw.png" />
	  <None Remove="Resources\Images\Flags\kz.png" />
	  <None Remove="Resources\Images\Flags\la.png" />
	  <None Remove="Resources\Images\Flags\lb.png" />
	  <None Remove="Resources\Images\Flags\lc.png" />
	  <None Remove="Resources\Images\Flags\li.png" />
	  <None Remove="Resources\Images\Flags\lk.png" />
	  <None Remove="Resources\Images\Flags\lr.png" />
	  <None Remove="Resources\Images\Flags\ls.png" />
	  <None Remove="Resources\Images\Flags\lt.png" />
	  <None Remove="Resources\Images\Flags\lu.png" />
	  <None Remove="Resources\Images\Flags\lv.png" />
	  <None Remove="Resources\Images\Flags\ly.png" />
	  <None Remove="Resources\Images\Flags\ma.png" />
	  <None Remove="Resources\Images\Flags\mc.png" />
	  <None Remove="Resources\Images\Flags\md.png" />
	  <None Remove="Resources\Images\Flags\me.png" />
	  <None Remove="Resources\Images\Flags\mg.png" />
	  <None Remove="Resources\Images\Flags\mh.png" />
	  <None Remove="Resources\Images\Flags\mk.png" />
	  <None Remove="Resources\Images\Flags\ml.png" />
	  <None Remove="Resources\Images\Flags\mm.png" />
	  <None Remove="Resources\Images\Flags\mn.png" />
	  <None Remove="Resources\Images\Flags\mr.png" />
	  <None Remove="Resources\Images\Flags\mt.png" />
	  <None Remove="Resources\Images\Flags\mu.png" />
	  <None Remove="Resources\Images\Flags\mv.png" />
	  <None Remove="Resources\Images\Flags\mw.png" />
	  <None Remove="Resources\Images\Flags\mx.png" />
	  <None Remove="Resources\Images\Flags\my.png" />
	  <None Remove="Resources\Images\Flags\mz.png" />
	  <None Remove="Resources\Images\Flags\na.png" />
	  <None Remove="Resources\Images\Flags\ne.png" />
	  <None Remove="Resources\Images\Flags\ng.png" />
	  <None Remove="Resources\Images\Flags\ni.png" />
	  <None Remove="Resources\Images\Flags\nl.png" />
	  <None Remove="Resources\Images\Flags\no.png" />
	  <None Remove="Resources\Images\Flags\np.png" />
	  <None Remove="Resources\Images\Flags\nr.png" />
	  <None Remove="Resources\Images\Flags\nz.png" />
	  <None Remove="Resources\Images\Flags\om.png" />
	  <None Remove="Resources\Images\Flags\pa.png" />
	  <None Remove="Resources\Images\Flags\pe.png" />
	  <None Remove="Resources\Images\Flags\pg.png" />
	  <None Remove="Resources\Images\Flags\ph.png" />
	  <None Remove="Resources\Images\Flags\pk.png" />
	  <None Remove="Resources\Images\Flags\pl.png" />
	  <None Remove="Resources\Images\Flags\pt.png" />
	  <None Remove="Resources\Images\Flags\pw.png" />
	  <None Remove="Resources\Images\Flags\py.png" />
	  <None Remove="Resources\Images\Flags\qa.png" />
	  <None Remove="Resources\Images\Flags\ro.png" />
	  <None Remove="Resources\Images\Flags\rs.png" />
	  <None Remove="Resources\Images\Flags\ru.png" />
	  <None Remove="Resources\Images\Flags\rw.png" />
	  <None Remove="Resources\Images\Flags\sa.png" />
	  <None Remove="Resources\Images\Flags\sb.png" />
	  <None Remove="Resources\Images\Flags\sc.png" />
	  <None Remove="Resources\Images\Flags\sd.png" />
	  <None Remove="Resources\Images\Flags\se.png" />
	  <None Remove="Resources\Images\Flags\sg.png" />
	  <None Remove="Resources\Images\Flags\si.png" />
	  <None Remove="Resources\Images\Flags\sk.png" />
	  <None Remove="Resources\Images\Flags\sl.png" />
	  <None Remove="Resources\Images\Flags\sm.png" />
	  <None Remove="Resources\Images\Flags\sn.png" />
	  <None Remove="Resources\Images\Flags\so.png" />
	  <None Remove="Resources\Images\Flags\sr.png" />
	  <None Remove="Resources\Images\Flags\ss.png" />
	  <None Remove="Resources\Images\Flags\st.png" />
	  <None Remove="Resources\Images\Flags\sv.png" />
	  <None Remove="Resources\Images\Flags\sy.png" />
	  <None Remove="Resources\Images\Flags\sz.png" />
	  <None Remove="Resources\Images\Flags\td.png" />
	  <None Remove="Resources\Images\Flags\tg.png" />
	  <None Remove="Resources\Images\Flags\th.png" />
	  <None Remove="Resources\Images\Flags\tj.png" />
	  <None Remove="Resources\Images\Flags\tl.png" />
	  <None Remove="Resources\Images\Flags\tm.png" />
	  <None Remove="Resources\Images\Flags\tn.png" />
	  <None Remove="Resources\Images\Flags\to.png" />
	  <None Remove="Resources\Images\Flags\tr.png" />
	  <None Remove="Resources\Images\Flags\tt.png" />
	  <None Remove="Resources\Images\Flags\tv.png" />
	  <None Remove="Resources\Images\Flags\tz.png" />
	  <None Remove="Resources\Images\Flags\ua.png" />
	  <None Remove="Resources\Images\Flags\ug.png" />
	  <None Remove="Resources\Images\Flags\us.png" />
	  <None Remove="Resources\Images\Flags\uy.png" />
	  <None Remove="Resources\Images\Flags\uz.png" />
	  <None Remove="Resources\Images\Flags\vc.png" />
	  <None Remove="Resources\Images\Flags\ve.png" />
	  <None Remove="Resources\Images\Flags\vn.png" />
	  <None Remove="Resources\Images\Flags\vu.png" />
	  <None Remove="Resources\Images\Flags\ws.png" />
	  <None Remove="Resources\Images\Flags\ye.png" />
	  <None Remove="Resources\Images\Flags\za.png" />
	  <None Remove="Resources\Images\Flags\zm.png" />
	  <None Remove="Resources\Images\Flags\zw.png" />
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Include="Resources\Images\Flags\ad.png" />
	  <MauiImage Include="Resources\Images\Flags\ae.png" />
	  <MauiImage Include="Resources\Images\Flags\af.png" />
	  <MauiImage Include="Resources\Images\Flags\ag.png" />
	  <MauiImage Include="Resources\Images\Flags\al.png" />
	  <MauiImage Include="Resources\Images\Flags\am.png" />
	  <MauiImage Include="Resources\Images\Flags\ao.png" />
	  <MauiImage Include="Resources\Images\Flags\ar.png" />
	  <MauiImage Include="Resources\Images\Flags\at.png" />
	  <MauiImage Include="Resources\Images\Flags\au.png" />
	  <MauiImage Include="Resources\Images\Flags\az.png" />
	  <MauiImage Include="Resources\Images\Flags\ba.png" />
	  <MauiImage Include="Resources\Images\Flags\bb.png" />
	  <MauiImage Include="Resources\Images\Flags\bd.png" />
	  <MauiImage Include="Resources\Images\Flags\be.png" />
	  <MauiImage Include="Resources\Images\Flags\bf.png" />
	  <MauiImage Include="Resources\Images\Flags\bg.png" />
	  <MauiImage Include="Resources\Images\Flags\bh.png" />
	  <MauiImage Include="Resources\Images\Flags\bi.png" />
	  <MauiImage Include="Resources\Images\Flags\bj.png" />
	  <MauiImage Include="Resources\Images\Flags\bn.png" />
	  <MauiImage Include="Resources\Images\Flags\bo.png" />
	  <MauiImage Include="Resources\Images\Flags\br.png" />
	  <MauiImage Include="Resources\Images\Flags\bs.png" />
	  <MauiImage Include="Resources\Images\Flags\bt.png" />
	  <MauiImage Include="Resources\Images\Flags\bw.png" />
	  <MauiImage Include="Resources\Images\Flags\by.png" />
	  <MauiImage Include="Resources\Images\Flags\bz.png" />
	  <MauiImage Include="Resources\Images\Flags\ca.png" />
	  <MauiImage Include="Resources\Images\Flags\cd.png" />
	  <MauiImage Include="Resources\Images\Flags\cf.png" />
	  <MauiImage Include="Resources\Images\Flags\cg.png" />
	  <MauiImage Include="Resources\Images\Flags\ch.png" />
	  <MauiImage Include="Resources\Images\Flags\ci.png" />
	  <MauiImage Include="Resources\Images\Flags\cl.png" />
	  <MauiImage Include="Resources\Images\Flags\cm.png" />
	  <MauiImage Include="Resources\Images\Flags\cn.png" />
	  <MauiImage Include="Resources\Images\Flags\co.png" />
	  <MauiImage Include="Resources\Images\Flags\cr.png" />
	  <MauiImage Include="Resources\Images\Flags\cu.png" />
	  <MauiImage Include="Resources\Images\Flags\cv.png" />
	  <MauiImage Include="Resources\Images\Flags\cy.png" />
	  <MauiImage Include="Resources\Images\Flags\cz.png" />
	  <MauiImage Include="Resources\Images\Flags\de.png" />
	  <MauiImage Include="Resources\Images\Flags\dj.png" />
	  <MauiImage Include="Resources\Images\Flags\dk.png" />
	  <MauiImage Include="Resources\Images\Flags\dm.png" />
	  <MauiImage Include="Resources\Images\Flags\do.png" />
	  <MauiImage Include="Resources\Images\Flags\dz.png" />
	  <MauiImage Include="Resources\Images\Flags\ec.png" />
	  <MauiImage Include="Resources\Images\Flags\ee.png" />
	  <MauiImage Include="Resources\Images\Flags\eg.png" />
	  <MauiImage Include="Resources\Images\Flags\er.png" />
	  <MauiImage Include="Resources\Images\Flags\es.png" />
	  <MauiImage Include="Resources\Images\Flags\et.png" />
	  <MauiImage Include="Resources\Images\Flags\fi.png" />
	  <MauiImage Include="Resources\Images\Flags\fj.png" />
	  <MauiImage Include="Resources\Images\Flags\fm.png" />
	  <MauiImage Include="Resources\Images\Flags\fr.png" />
	  <MauiImage Include="Resources\Images\Flags\ga.png" />
	  <MauiImage Include="Resources\Images\Flags\gb.png" />
	  <MauiImage Include="Resources\Images\Flags\gd.png" />
	  <MauiImage Include="Resources\Images\Flags\ge.png" />
	  <MauiImage Include="Resources\Images\Flags\gh.png" />
	  <MauiImage Include="Resources\Images\Flags\gm.png" />
	  <MauiImage Include="Resources\Images\Flags\gn.png" />
	  <MauiImage Include="Resources\Images\Flags\gq.png" />
	  <MauiImage Include="Resources\Images\Flags\gr.png" />
	  <MauiImage Include="Resources\Images\Flags\gt.png" />
	  <MauiImage Include="Resources\Images\Flags\gw.png" />
	  <MauiImage Include="Resources\Images\Flags\gy.png" />
	  <MauiImage Include="Resources\Images\Flags\hn.png" />
	  <MauiImage Include="Resources\Images\Flags\hr.png" />
	  <MauiImage Include="Resources\Images\Flags\ht.png" />
	  <MauiImage Include="Resources\Images\Flags\hu.png" />
	  <MauiImage Include="Resources\Images\Flags\id.png" />
	  <MauiImage Include="Resources\Images\Flags\ie.png" />
	  <MauiImage Include="Resources\Images\Flags\il.png" />
	  <MauiImage Include="Resources\Images\Flags\in.png" />
	  <MauiImage Include="Resources\Images\Flags\iq.png" />
	  <MauiImage Include="Resources\Images\Flags\ir.png" />
	  <MauiImage Include="Resources\Images\Flags\is.png" />
	  <MauiImage Include="Resources\Images\Flags\it.png" />
	  <MauiImage Include="Resources\Images\Flags\jm.png" />
	  <MauiImage Include="Resources\Images\Flags\jo.png" />
	  <MauiImage Include="Resources\Images\Flags\jp.png" />
	  <MauiImage Include="Resources\Images\Flags\ke.png" />
	  <MauiImage Include="Resources\Images\Flags\kg.png" />
	  <MauiImage Include="Resources\Images\Flags\kh.png" />
	  <MauiImage Include="Resources\Images\Flags\ki.png" />
	  <MauiImage Include="Resources\Images\Flags\km.png" />
	  <MauiImage Include="Resources\Images\Flags\kn.png" />
	  <MauiImage Include="Resources\Images\Flags\kp.png" />
	  <MauiImage Include="Resources\Images\Flags\kr.png" />
	  <MauiImage Include="Resources\Images\Flags\kw.png" />
	  <MauiImage Include="Resources\Images\Flags\kz.png" />
	  <MauiImage Include="Resources\Images\Flags\la.png" />
	  <MauiImage Include="Resources\Images\Flags\lb.png" />
	  <MauiImage Include="Resources\Images\Flags\lc.png" />
	  <MauiImage Include="Resources\Images\Flags\li.png" />
	  <MauiImage Include="Resources\Images\Flags\lk.png" />
	  <MauiImage Include="Resources\Images\Flags\lr.png" />
	  <MauiImage Include="Resources\Images\Flags\ls.png" />
	  <MauiImage Include="Resources\Images\Flags\lt.png" />
	  <MauiImage Include="Resources\Images\Flags\lu.png" />
	  <MauiImage Include="Resources\Images\Flags\lv.png" />
	  <MauiImage Include="Resources\Images\Flags\ly.png" />
	  <MauiImage Include="Resources\Images\Flags\ma.png" />
	  <MauiImage Include="Resources\Images\Flags\mc.png" />
	  <MauiImage Include="Resources\Images\Flags\md.png" />
	  <MauiImage Include="Resources\Images\Flags\me.png" />
	  <MauiImage Include="Resources\Images\Flags\mg.png" />
	  <MauiImage Include="Resources\Images\Flags\mh.png" />
	  <MauiImage Include="Resources\Images\Flags\mk.png" />
	  <MauiImage Include="Resources\Images\Flags\ml.png" />
	  <MauiImage Include="Resources\Images\Flags\mm.png" />
	  <MauiImage Include="Resources\Images\Flags\mn.png" />
	  <MauiImage Include="Resources\Images\Flags\mr.png" />
	  <MauiImage Include="Resources\Images\Flags\mt.png" />
	  <MauiImage Include="Resources\Images\Flags\mu.png" />
	  <MauiImage Include="Resources\Images\Flags\mv.png" />
	  <MauiImage Include="Resources\Images\Flags\mw.png" />
	  <MauiImage Include="Resources\Images\Flags\mx.png" />
	  <MauiImage Include="Resources\Images\Flags\my.png" />
	  <MauiImage Include="Resources\Images\Flags\mz.png" />
	  <MauiImage Include="Resources\Images\Flags\na.png" />
	  <MauiImage Include="Resources\Images\Flags\ne.png" />
	  <MauiImage Include="Resources\Images\Flags\ng.png" />
	  <MauiImage Include="Resources\Images\Flags\ni.png" />
	  <MauiImage Include="Resources\Images\Flags\nl.png" />
	  <MauiImage Include="Resources\Images\Flags\no.png" />
	  <MauiImage Include="Resources\Images\Flags\np.png" />
	  <MauiImage Include="Resources\Images\Flags\nr.png" />
	  <MauiImage Include="Resources\Images\Flags\nz.png" />
	  <MauiImage Include="Resources\Images\Flags\om.png" />
	  <MauiImage Include="Resources\Images\Flags\pa.png" />
	  <MauiImage Include="Resources\Images\Flags\pe.png" />
	  <MauiImage Include="Resources\Images\Flags\pg.png" />
	  <MauiImage Include="Resources\Images\Flags\ph.png" />
	  <MauiImage Include="Resources\Images\Flags\pk.png" />
	  <MauiImage Include="Resources\Images\Flags\pl.png" />
	  <MauiImage Include="Resources\Images\Flags\pt.png" />
	  <MauiImage Include="Resources\Images\Flags\pw.png" />
	  <MauiImage Include="Resources\Images\Flags\py.png" />
	  <MauiImage Include="Resources\Images\Flags\qa.png" />
	  <MauiImage Include="Resources\Images\Flags\ro.png" />
	  <MauiImage Include="Resources\Images\Flags\rs.png" />
	  <MauiImage Include="Resources\Images\Flags\ru.png" />
	  <MauiImage Include="Resources\Images\Flags\rw.png" />
	  <MauiImage Include="Resources\Images\Flags\sa.png" />
	  <MauiImage Include="Resources\Images\Flags\sb.png" />
	  <MauiImage Include="Resources\Images\Flags\sc.png" />
	  <MauiImage Include="Resources\Images\Flags\sd.png" />
	  <MauiImage Include="Resources\Images\Flags\se.png" />
	  <MauiImage Include="Resources\Images\Flags\sg.png" />
	  <MauiImage Include="Resources\Images\Flags\si.png" />
	  <MauiImage Include="Resources\Images\Flags\sk.png" />
	  <MauiImage Include="Resources\Images\Flags\sl.png" />
	  <MauiImage Include="Resources\Images\Flags\sm.png" />
	  <MauiImage Include="Resources\Images\Flags\sn.png" />
	  <MauiImage Include="Resources\Images\Flags\so.png" />
	  <MauiImage Include="Resources\Images\Flags\sr.png" />
	  <MauiImage Include="Resources\Images\Flags\ss.png" />
	  <MauiImage Include="Resources\Images\Flags\st.png" />
	  <MauiImage Include="Resources\Images\Flags\sv.png" />
	  <MauiImage Include="Resources\Images\Flags\sy.png" />
	  <MauiImage Include="Resources\Images\Flags\sz.png" />
	  <MauiImage Include="Resources\Images\Flags\td.png" />
	  <MauiImage Include="Resources\Images\Flags\tg.png" />
	  <MauiImage Include="Resources\Images\Flags\th.png" />
	  <MauiImage Include="Resources\Images\Flags\tj.png" />
	  <MauiImage Include="Resources\Images\Flags\tl.png" />
	  <MauiImage Include="Resources\Images\Flags\tm.png" />
	  <MauiImage Include="Resources\Images\Flags\tn.png" />
	  <MauiImage Include="Resources\Images\Flags\to.png" />
	  <MauiImage Include="Resources\Images\Flags\tr.png" />
	  <MauiImage Include="Resources\Images\Flags\tt.png" />
	  <MauiImage Include="Resources\Images\Flags\tv.png" />
	  <MauiImage Include="Resources\Images\Flags\tz.png" />
	  <MauiImage Include="Resources\Images\Flags\ua.png" />
	  <MauiImage Include="Resources\Images\Flags\ug.png" />
	  <MauiImage Include="Resources\Images\Flags\us.png" />
	  <MauiImage Include="Resources\Images\Flags\uy.png" />
	  <MauiImage Include="Resources\Images\Flags\uz.png" />
	  <MauiImage Include="Resources\Images\Flags\vc.png" />
	  <MauiImage Include="Resources\Images\Flags\ve.png" />
	  <MauiImage Include="Resources\Images\Flags\vn.png" />
	  <MauiImage Include="Resources\Images\Flags\vu.png" />
	  <MauiImage Include="Resources\Images\Flags\ws.png" />
	  <MauiImage Include="Resources\Images\Flags\ye.png" />
	  <MauiImage Include="Resources\Images\Flags\za.png" />
	  <MauiImage Include="Resources\Images\Flags\zm.png" />
	  <MauiImage Include="Resources\Images\Flags\zw.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui.Core" />
		<PackageReference Include="Microsoft.Maui.Controls" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\House.Of.Arbitration.Data.Abstractions\House.Of.Arbitration.Data.Abstractions.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.Data\House.Of.Arbitration.Data.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.Localization\House.Of.Arbitration.Localization.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.Models\House.Of.Arbitration.Models.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.Services.Abstractions\House.Of.Arbitration.Services.Abstractions.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.Services\House.Of.Arbitration.Services.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.ViewModels.Core\House.Of.Arbitration.ViewModels.Core.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.ViewModels\House.Of.Arbitration.ViewModels.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.Views.Core\House.Of.Arbitration.Views.Core.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.Views\House.Of.Arbitration.Views.csproj" />
	  <ProjectReference Include="..\House.Of.Arbitration.Controls\House.Of.Arbitration.Controls.csproj" />
	</ItemGroup>

</Project>
