using CommunityToolkit.Mvvm.ComponentModel;

namespace House.Of.Arbitration.Models;

public partial class CountryModel : ObservableObject
{
    public string IsoCode { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;

    public static List<CountryModel> DefaultCountries = new List<CountryModel>
    {
        new CountryModel { IsoCode = "AF", Name = "Afghanistan" },
        new CountryModel { IsoCode = "AL", Name = "Albanie" },
        new CountryModel { IsoCode = "DZ", Name = "Algérie" },
        new CountryModel { IsoCode = "AD", Name = "Andorre" },
        new CountryModel { IsoCode = "AO", Name = "Angola" },
        new CountryModel { IsoCode = "AG", Name = "Antigua-et-Barbuda" },
        new CountryModel { IsoCode = "AR", Name = "Argentine" },
        new CountryModel { IsoCode = "AM", Name = "Arménie" },
        new CountryModel { IsoCode = "AU", Name = "Australie" },
        new CountryModel { IsoCode = "AT", Name = "Autriche" },
        new CountryModel { IsoCode = "AZ", Name = "Azerbaïdjan" },
        new CountryModel { IsoCode = "BS", Name = "Bahamas" },
        new CountryModel { IsoCode = "BH", Name = "Bahreïn" },
        new CountryModel { IsoCode = "BD", Name = "Bangladesh" },
        new CountryModel { IsoCode = "BB", Name = "Barbade" },
        new CountryModel { IsoCode = "BY", Name = "Biélorussie" },
        new CountryModel { IsoCode = "BE", Name = "Belgique" },
        new CountryModel { IsoCode = "BZ", Name = "Belize" },
        new CountryModel { IsoCode = "BJ", Name = "Bénin" },
        new CountryModel { IsoCode = "BT", Name = "Bhoutan" },
        new CountryModel { IsoCode = "BO", Name = "Bolivie" },
        new CountryModel { IsoCode = "BA", Name = "Bosnie-Herzégovine" },
        new CountryModel { IsoCode = "BW", Name = "Botswana" },
        new CountryModel { IsoCode = "BR", Name = "Brésil" },
        new CountryModel { IsoCode = "BN", Name = "Brunei" },
        new CountryModel { IsoCode = "BG", Name = "Bulgarie" },
        new CountryModel { IsoCode = "BF", Name = "Burkina Faso" },
        new CountryModel { IsoCode = "BI", Name = "Burundi" },
        new CountryModel { IsoCode = "KH", Name = "Cambodge" },
        new CountryModel { IsoCode = "CM", Name = "Cameroun" },
        new CountryModel { IsoCode = "CA", Name = "Canada" },
        new CountryModel { IsoCode = "CV", Name = "Cap-Vert" },
        new CountryModel { IsoCode = "CF", Name = "République centrafricaine" },
        new CountryModel { IsoCode = "TD", Name = "Tchad" },
        new CountryModel { IsoCode = "CL", Name = "Chili" },
        new CountryModel { IsoCode = "CN", Name = "Chine" },
        new CountryModel { IsoCode = "CO", Name = "Colombie" },
        new CountryModel { IsoCode = "KM", Name = "Comores" },
        new CountryModel { IsoCode = "CG", Name = "Congo" },
        new CountryModel { IsoCode = "CD", Name = "Congo (Rép. dém.)" },
        new CountryModel { IsoCode = "CR", Name = "Costa Rica" },
        new CountryModel { IsoCode = "CI", Name = "Côte d'Ivoire" },
        new CountryModel { IsoCode = "HR", Name = "Croatie" },
        new CountryModel { IsoCode = "CU", Name = "Cuba" },
        new CountryModel { IsoCode = "CY", Name = "Chypre" },
        new CountryModel { IsoCode = "CZ", Name = "République tchèque" },
        new CountryModel { IsoCode = "DK", Name = "Danemark" },
        new CountryModel { IsoCode = "DJ", Name = "Djibouti" },
        new CountryModel { IsoCode = "DM", Name = "Dominique" },
        new CountryModel { IsoCode = "DO", Name = "République dominicaine" },
        new CountryModel { IsoCode = "EC", Name = "Équateur" },
        new CountryModel { IsoCode = "EG", Name = "Égypte" },
        new CountryModel { IsoCode = "SV", Name = "Salvador" },
        new CountryModel { IsoCode = "GQ", Name = "Guinée équatoriale" },
        new CountryModel { IsoCode = "ER", Name = "Érythrée" },
        new CountryModel { IsoCode = "EE", Name = "Estonie" },
        new CountryModel { IsoCode = "ET", Name = "Éthiopie" },
        new CountryModel { IsoCode = "FJ", Name = "Fidji" },
        new CountryModel { IsoCode = "FI", Name = "Finlande" },
        new CountryModel { IsoCode = "FR", Name = "France" },
        new CountryModel { IsoCode = "GA", Name = "Gabon" },
        new CountryModel { IsoCode = "GM", Name = "Gambie" },
        new CountryModel { IsoCode = "GE", Name = "Géorgie" },
        new CountryModel { IsoCode = "DE", Name = "Allemagne" },
        new CountryModel { IsoCode = "GH", Name = "Ghana" },
        new CountryModel { IsoCode = "GR", Name = "Grèce" },
        new CountryModel { IsoCode = "GD", Name = "Grenade" },
        new CountryModel { IsoCode = "GT", Name = "Guatemala" },
        new CountryModel { IsoCode = "GN", Name = "Guinée" },
        new CountryModel { IsoCode = "GW", Name = "Guinée-Bissau" },
        new CountryModel { IsoCode = "GY", Name = "Guyana" },
        new CountryModel { IsoCode = "HT", Name = "Haïti" },
        new CountryModel { IsoCode = "HN", Name = "Honduras" },
        new CountryModel { IsoCode = "HU", Name = "Hongrie" },
        new CountryModel { IsoCode = "IS", Name = "Islande" },
        new CountryModel { IsoCode = "IN", Name = "Inde" },
        new CountryModel { IsoCode = "ID", Name = "Indonésie" },
        new CountryModel { IsoCode = "IR", Name = "Iran" },
        new CountryModel { IsoCode = "IQ", Name = "Irak" },
        new CountryModel { IsoCode = "IE", Name = "Irlande" },
        new CountryModel { IsoCode = "IL", Name = "Israël" },
        new CountryModel { IsoCode = "IT", Name = "Italie" },
        new CountryModel { IsoCode = "JM", Name = "Jamaïque" },
        new CountryModel { IsoCode = "JP", Name = "Japon" },
        new CountryModel { IsoCode = "JO", Name = "Jordanie" },
        new CountryModel { IsoCode = "KZ", Name = "Kazakhstan" },
        new CountryModel { IsoCode = "KE", Name = "Kenya" },
        new CountryModel { IsoCode = "KI", Name = "Kiribati" },
        new CountryModel { IsoCode = "KP", Name = "Corée du Nord" },
        new CountryModel { IsoCode = "KR", Name = "Corée du Sud" },
        new CountryModel { IsoCode = "KW", Name = "Koweït" },
        new CountryModel { IsoCode = "KG", Name = "Kirghizistan" },
        new CountryModel { IsoCode = "LA", Name = "Laos" },
        new CountryModel { IsoCode = "LV", Name = "Lettonie" },
        new CountryModel { IsoCode = "LB", Name = "Liban" },
        new CountryModel { IsoCode = "LS", Name = "Lesotho" },
        new CountryModel { IsoCode = "LR", Name = "Liberia" },
        new CountryModel { IsoCode = "LY", Name = "Libye" },
        new CountryModel { IsoCode = "LI", Name = "Liechtenstein" },
        new CountryModel { IsoCode = "LT", Name = "Lituanie" },
        new CountryModel { IsoCode = "LU", Name = "Luxembourg" },
        new CountryModel { IsoCode = "MK", Name = "Macédoine du Nord" },
        new CountryModel { IsoCode = "MG", Name = "Madagascar" },
        new CountryModel { IsoCode = "MW", Name = "Malawi" },
        new CountryModel { IsoCode = "MY", Name = "Malaisie" },
        new CountryModel { IsoCode = "MV", Name = "Maldives" },
        new CountryModel { IsoCode = "ML", Name = "Mali" },
        new CountryModel { IsoCode = "MT", Name = "Malte" },
        new CountryModel { IsoCode = "MH", Name = "Îles Marshall" },
        new CountryModel { IsoCode = "MR", Name = "Mauritanie" },
        new CountryModel { IsoCode = "MU", Name = "Maurice" },
        new CountryModel { IsoCode = "MX", Name = "Mexique" },
        new CountryModel { IsoCode = "FM", Name = "Micronésie" },
        new CountryModel { IsoCode = "MD", Name = "Moldavie" },
        new CountryModel { IsoCode = "MC", Name = "Monaco" },
        new CountryModel { IsoCode = "MN", Name = "Mongolie" },
        new CountryModel { IsoCode = "ME", Name = "Monténégro" },
        new CountryModel { IsoCode = "MA", Name = "Maroc" },
        new CountryModel { IsoCode = "MZ", Name = "Mozambique" },
        new CountryModel { IsoCode = "MM", Name = "Myanmar" },
        new CountryModel { IsoCode = "NA", Name = "Namibie" },
        new CountryModel { IsoCode = "NR", Name = "Nauru" },
        new CountryModel { IsoCode = "NP", Name = "Népal" },
        new CountryModel { IsoCode = "NL", Name = "Pays-Bas" },
        new CountryModel { IsoCode = "NZ", Name = "Nouvelle-Zélande" },
        new CountryModel { IsoCode = "NI", Name = "Nicaragua" },
        new CountryModel { IsoCode = "NE", Name = "Niger" },
        new CountryModel { IsoCode = "NG", Name = "Nigeria" },
        new CountryModel { IsoCode = "NO", Name = "Norvège" },
        new CountryModel { IsoCode = "OM", Name = "Oman" },
        new CountryModel { IsoCode = "PK", Name = "Pakistan" },
        new CountryModel { IsoCode = "PW", Name = "Palaos" },
        new CountryModel { IsoCode = "PA", Name = "Panama" },
        new CountryModel { IsoCode = "PG", Name = "Papouasie-Nouvelle-Guinée" },
        new CountryModel { IsoCode = "PY", Name = "Paraguay" },
        new CountryModel { IsoCode = "PE", Name = "Pérou" },
        new CountryModel { IsoCode = "PH", Name = "Philippines" },
        new CountryModel { IsoCode = "PL", Name = "Pologne" },
        new CountryModel { IsoCode = "PT", Name = "Portugal" },
        new CountryModel { IsoCode = "QA", Name = "Qatar" },
        new CountryModel { IsoCode = "RO", Name = "Roumanie" },
        new CountryModel { IsoCode = "RU", Name = "Russie" },
        new CountryModel { IsoCode = "RW", Name = "Rwanda" },
        new CountryModel { IsoCode = "KN", Name = "Saint-Christophe-et-Niévès" },
        new CountryModel { IsoCode = "LC", Name = "Sainte-Lucie" },
        new CountryModel { IsoCode = "VC", Name = "Saint-Vincent-et-les-Grenadines" },
        new CountryModel { IsoCode = "WS", Name = "Samoa" },
        new CountryModel { IsoCode = "SM", Name = "Saint-Marin" },
        new CountryModel { IsoCode = "ST", Name = "Sao Tomé-et-Principe" },
        new CountryModel { IsoCode = "SA", Name = "Arabie saoudite" },
        new CountryModel { IsoCode = "SN", Name = "Sénégal" },
        new CountryModel { IsoCode = "RS", Name = "Serbie" },
        new CountryModel { IsoCode = "SC", Name = "Seychelles" },
        new CountryModel { IsoCode = "SL", Name = "Sierra Leone" },
        new CountryModel { IsoCode = "SG", Name = "Singapour" },
        new CountryModel { IsoCode = "SK", Name = "Slovaquie" },
        new CountryModel { IsoCode = "SI", Name = "Slovénie" },
        new CountryModel { IsoCode = "SB", Name = "Îles Salomon" },
        new CountryModel { IsoCode = "SO", Name = "Somalie" },
        new CountryModel { IsoCode = "ZA", Name = "Afrique du Sud" },
        new CountryModel { IsoCode = "SS", Name = "Soudan du Sud" },
        new CountryModel { IsoCode = "ES", Name = "Espagne" },
        new CountryModel { IsoCode = "LK", Name = "Sri Lanka" },
        new CountryModel { IsoCode = "SD", Name = "Soudan" },
        new CountryModel { IsoCode = "SR", Name = "Suriname" },
        new CountryModel { IsoCode = "SZ", Name = "Eswatini" },
        new CountryModel { IsoCode = "SE", Name = "Suède" },
        new CountryModel { IsoCode = "CH", Name = "Suisse" },
        new CountryModel { IsoCode = "SY", Name = "Syrie" },
        new CountryModel { IsoCode = "TJ", Name = "Tadjikistan" },
        new CountryModel { IsoCode = "TZ", Name = "Tanzanie" },
        new CountryModel { IsoCode = "TH", Name = "Thaïlande" },
        new CountryModel { IsoCode = "TL", Name = "Timor oriental" },
        new CountryModel { IsoCode = "TG", Name = "Togo" },
        new CountryModel { IsoCode = "TO", Name = "Tonga" },
        new CountryModel { IsoCode = "TT", Name = "Trinité-et-Tobago" },
        new CountryModel { IsoCode = "TN", Name = "Tunisie" },
        new CountryModel { IsoCode = "TR", Name = "Turquie" },
        new CountryModel { IsoCode = "TM", Name = "Turkménistan" },
        new CountryModel { IsoCode = "TV", Name = "Tuvalu" },
        new CountryModel { IsoCode = "UG", Name = "Ouganda" },
        new CountryModel { IsoCode = "UA", Name = "Ukraine" },
        new CountryModel { IsoCode = "AE", Name = "Émirats arabes unis" },
        new CountryModel { IsoCode = "GB", Name = "Royaume-Uni" },
        new CountryModel { IsoCode = "US", Name = "États-Unis" },
        new CountryModel { IsoCode = "UY", Name = "Uruguay" },
        new CountryModel { IsoCode = "UZ", Name = "Ouzbékistan" },
        new CountryModel { IsoCode = "VU", Name = "Vanuatu" },
        new CountryModel { IsoCode = "VE", Name = "Venezuela" },
        new CountryModel { IsoCode = "VN", Name = "Vietnam" },
        new CountryModel { IsoCode = "YE", Name = "Yémen" },
        new CountryModel { IsoCode = "ZM", Name = "Zambie" },
        new CountryModel { IsoCode = "ZW", Name = "Zimbabwe" }
    };
}
