//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace House.Of.Arbitration.Localization;

/// <summary>
/// Provides strongly-typed access to localized resources. This class is auto-generated by a T4 template
/// to expose each resource key as a property, enabling compile-time safety and autocompletion in XAML.
/// </summary>
public class ResourceProvider : INotifyPropertyChanged
{
    /// <summary>
    /// Occurs when a property value changes.
    /// </summary>
    public event PropertyChangedEventHandler PropertyChanged;

    /// <summary>
    /// Gets the translated "APPLICATION_NAME" string.
    /// </summary>
    public string APPLICATION_NAME =>
LocalizationResourceManager.Instance.GetValue(nameof(APPLICATION_NAME));
    /// <summary>
    /// Gets the translated "ADD_COMPETITION" string.
    /// </summary>
    public string ADD_COMPETITION =>
LocalizationResourceManager.Instance.GetValue(nameof(ADD_COMPETITION));
    /// <summary>
    /// Gets the translated "START_COMPETITION" string.
    /// </summary>
    public string START_COMPETITION =>
LocalizationResourceManager.Instance.GetValue(nameof(START_COMPETITION));

    /// <summary>
    /// Initializes a new instance of the <see cref="ResourceProvider"/> class.
    /// Subscribes to the <see cref="LocalizationResourceManager"/>'s PropertyChanged event
    /// to refresh all bindings when the culture changes.
    /// </summary>
    public ResourceProvider()
    {
        LocalizationResourceManager.Instance.PropertyChanged += (sender, args) =>
        {
            OnPropertyChanged(null); // This will refresh all properties
        };
    }

    /// <summary>
    /// Raises the PropertyChanged event.
    /// </summary>
    /// <param name="propertyName">The name of the property that changed.</param>
    protected void OnPropertyChanged([CallerMemberName] string propertyName = "")
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
