//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace House.Of.Arbitration.Localization;

/// <summary>
/// Provides strongly-typed access to localized resources. This class is auto-generated by a T4 template
/// to expose each resource key as a property, enabling compile-time safety and autocompletion in XAML.
/// </summary>
public class ResourceProvider : INotifyPropertyChanged
{
    /// <summary>
    /// Occurs when a property value changes.
    /// </summary>
    public event PropertyChangedEventHandler PropertyChanged;

    /// <summary>
    /// Gets the translated "APPLICATION_NAME" string.
    /// </summary>
    public string APPLICATION_NAME =>
LocalizationResourceManager.Instance.GetValue(nameof(APPLICATION_NAME));
    /// <summary>
    /// Gets the translated "ADD_COMPETITION" string.
    /// </summary>
    public string ADD_COMPETITION =>
LocalizationResourceManager.Instance.GetValue(nameof(ADD_COMPETITION));
    /// <summary>
    /// Gets the translated "START_COMPETITION" string.
    /// </summary>
    public string START_COMPETITION =>
LocalizationResourceManager.Instance.GetValue(nameof(START_COMPETITION));
    /// <summary>
    /// Gets the translated "MASTER" string.
    /// </summary>
    public string MASTER =>
LocalizationResourceManager.Instance.GetValue(nameof(MASTER));
    /// <summary>
    /// Gets the translated "SLAVE" string.
    /// </summary>
    public string SLAVE =>
LocalizationResourceManager.Instance.GetValue(nameof(SLAVE));
    /// <summary>
    /// Gets the translated "COMPETITION_LIST" string.
    /// </summary>
    public string COMPETITION_LIST =>
LocalizationResourceManager.Instance.GetValue(nameof(COMPETITION_LIST));
    /// <summary>
    /// Gets the translated "NO_COMPETITION" string.
    /// </summary>
    public string NO_COMPETITION =>
LocalizationResourceManager.Instance.GetValue(nameof(NO_COMPETITION));
    /// <summary>
    /// Gets the translated "PLACEHOLDER_COMPETITION_NAME" string.
    /// </summary>
    public string PLACEHOLDER_COMPETITION_NAME =>
LocalizationResourceManager.Instance.GetValue(nameof(PLACEHOLDER_COMPETITION_NAME));
    /// <summary>
    /// Gets the translated "NAME_REQUIRED" string.
    /// </summary>
    public string NAME_REQUIRED =>
LocalizationResourceManager.Instance.GetValue(nameof(NAME_REQUIRED));
    /// <summary>
    /// Gets the translated "COMPETITION_NAME" string.
    /// </summary>
    public string COMPETITION_NAME =>
LocalizationResourceManager.Instance.GetValue(nameof(COMPETITION_NAME));
    /// <summary>
    /// Gets the translated "COMPETITION_DATE" string.
    /// </summary>
    public string COMPETITION_DATE =>
LocalizationResourceManager.Instance.GetValue(nameof(COMPETITION_DATE));
    /// <summary>
    /// Gets the translated "PREVIOUS" string.
    /// </summary>
    public string PREVIOUS =>
LocalizationResourceManager.Instance.GetValue(nameof(PREVIOUS));
    /// <summary>
    /// Gets the translated "NEXT" string.
    /// </summary>
    public string NEXT =>
LocalizationResourceManager.Instance.GetValue(nameof(NEXT));
    /// <summary>
    /// Gets the translated "VALIDATE_ACTION" string.
    /// </summary>
    public string VALIDATE_ACTION =>
LocalizationResourceManager.Instance.GetValue(nameof(VALIDATE_ACTION));
    /// <summary>
    /// Gets the translated "CATEGORY_LIST" string.
    /// </summary>
    public string CATEGORY_LIST =>
LocalizationResourceManager.Instance.GetValue(nameof(CATEGORY_LIST));
    /// <summary>
    /// Gets the translated "ADD_CATEGORY" string.
    /// </summary>
    public string ADD_CATEGORY =>
LocalizationResourceManager.Instance.GetValue(nameof(ADD_CATEGORY));
    /// <summary>
    /// Gets the translated "COMPETITION_SETTINGS" string.
    /// </summary>
    public string COMPETITION_SETTINGS =>
LocalizationResourceManager.Instance.GetValue(nameof(COMPETITION_SETTINGS));
    /// <summary>
    /// Gets the translated "NEW_CATEGORY" string.
    /// </summary>
    public string NEW_CATEGORY =>
LocalizationResourceManager.Instance.GetValue(nameof(NEW_CATEGORY));
    /// <summary>
    /// Gets the translated "STYLE" string.
    /// </summary>
    public string STYLE =>
LocalizationResourceManager.Instance.GetValue(nameof(STYLE));
    /// <summary>
    /// Gets the translated "ROUND_TYPE" string.
    /// </summary>
    public string ROUND_TYPE =>
LocalizationResourceManager.Instance.GetValue(nameof(ROUND_TYPE));
    /// <summary>
    /// Gets the translated "GENRE" string.
    /// </summary>
    public string GENRE =>
LocalizationResourceManager.Instance.GetValue(nameof(GENRE));
    /// <summary>
    /// Gets the translated "OLD" string.
    /// </summary>
    public string OLD =>
LocalizationResourceManager.Instance.GetValue(nameof(OLD));
    /// <summary>
    /// Gets the translated "WEIGHT_MIN" string.
    /// </summary>
    public string WEIGHT_MIN =>
LocalizationResourceManager.Instance.GetValue(nameof(WEIGHT_MIN));
    /// <summary>
    /// Gets the translated "WEIGHT_MAX" string.
    /// </summary>
    public string WEIGHT_MAX =>
LocalizationResourceManager.Instance.GetValue(nameof(WEIGHT_MAX));
    /// <summary>
    /// Gets the translated "CLOSE_ACTION" string.
    /// </summary>
    public string CLOSE_ACTION =>
LocalizationResourceManager.Instance.GetValue(nameof(CLOSE_ACTION));
    /// <summary>
    /// Gets the translated "ENUM_CATEGORY_SANDA" string.
    /// </summary>
    public string ENUM_CATEGORY_SANDA =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_CATEGORY_SANDA));
    /// <summary>
    /// Gets the translated "ENUM_CATEGORY_SANDALIGHT" string.
    /// </summary>
    public string ENUM_CATEGORY_SANDALIGHT =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_CATEGORY_SANDALIGHT));
    /// <summary>
    /// Gets the translated "ENUM_CATEGORY_NONE" string.
    /// </summary>
    public string ENUM_CATEGORY_NONE =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_CATEGORY_NONE));
    /// <summary>
    /// Gets the translated "ENUM_CATEGORY_TAOLU" string.
    /// </summary>
    public string ENUM_CATEGORY_TAOLU =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_CATEGORY_TAOLU));
    /// <summary>
    /// Gets the translated "ENUM_ROUND_ELIMINATION" string.
    /// </summary>
    public string ENUM_ROUND_ELIMINATION =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_ROUND_ELIMINATION));
    /// <summary>
    /// Gets the translated "ENUM_ROUND_NONE" string.
    /// </summary>
    public string ENUM_ROUND_NONE =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_ROUND_NONE));
    /// <summary>
    /// Gets the translated "ENUM_ROUND_ROBIN" string.
    /// </summary>
    public string ENUM_ROUND_ROBIN =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_ROUND_ROBIN));
    /// <summary>
    /// Gets the translated "ENUM_GENRE_NONE" string.
    /// </summary>
    public string ENUM_GENRE_NONE =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_GENRE_NONE));
    /// <summary>
    /// Gets the translated "ENUM_GENRE_MEN" string.
    /// </summary>
    public string ENUM_GENRE_MEN =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_GENRE_MEN));
    /// <summary>
    /// Gets the translated "ENUM_GENRE_WOMEN" string.
    /// </summary>
    public string ENUM_GENRE_WOMEN =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_GENRE_WOMEN));
    /// <summary>
    /// Gets the translated "ENUM_AGE_NONE" string.
    /// </summary>
    public string ENUM_AGE_NONE =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_AGE_NONE));
    /// <summary>
    /// Gets the translated "ENUM_AGE_CADETS" string.
    /// </summary>
    public string ENUM_AGE_CADETS =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_AGE_CADETS));
    /// <summary>
    /// Gets the translated "ENUM_AGE_JUNIORS" string.
    /// </summary>
    public string ENUM_AGE_JUNIORS =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_AGE_JUNIORS));
    /// <summary>
    /// Gets the translated "ENUM_AGE_SENIORS" string.
    /// </summary>
    public string ENUM_AGE_SENIORS =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_AGE_SENIORS));
    /// <summary>
    /// Gets the translated "ENUM_AGE_ESPOIRS" string.
    /// </summary>
    public string ENUM_AGE_ESPOIRS =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_AGE_ESPOIRS));
    /// <summary>
    /// Gets the translated "ENUM_AGE_VETERANS" string.
    /// </summary>
    public string ENUM_AGE_VETERANS =>
LocalizationResourceManager.Instance.GetValue(nameof(ENUM_AGE_VETERANS));
    /// <summary>
    /// Gets the translated "WEIGHT_UNIT" string.
    /// </summary>
    public string WEIGHT_UNIT =>
LocalizationResourceManager.Instance.GetValue(nameof(WEIGHT_UNIT));
    /// <summary>
    /// Gets the translated "COMPETITORS" string.
    /// </summary>
    public string COMPETITORS =>
LocalizationResourceManager.Instance.GetValue(nameof(COMPETITORS));
    /// <summary>
    /// Gets the translated "ADD_COMPETITOR" string.
    /// </summary>
    public string ADD_COMPETITOR =>
LocalizationResourceManager.Instance.GetValue(nameof(ADD_COMPETITOR));
    /// <summary>
    /// Gets the translated "NO_COMPETITORS" string.
    /// </summary>
    public string NO_COMPETITORS =>
LocalizationResourceManager.Instance.GetValue(nameof(NO_COMPETITORS));
    /// <summary>
    /// Gets the translated "COMPETITOR" string.
    /// </summary>
    public string COMPETITOR =>
LocalizationResourceManager.Instance.GetValue(nameof(COMPETITOR));
    /// <summary>
    /// Gets the translated "FIRSTNAME" string.
    /// </summary>
    public string FIRSTNAME =>
LocalizationResourceManager.Instance.GetValue(nameof(FIRSTNAME));
    /// <summary>
    /// Gets the translated "LASTNAME" string.
    /// </summary>
    public string LASTNAME =>
LocalizationResourceManager.Instance.GetValue(nameof(LASTNAME));
    /// <summary>
    /// Gets the translated "CLUB" string.
    /// </summary>
    public string CLUB =>
LocalizationResourceManager.Instance.GetValue(nameof(CLUB));
    /// <summary>
    /// Gets the translated "GRADE" string.
    /// </summary>
    public string GRADE =>
LocalizationResourceManager.Instance.GetValue(nameof(GRADE));
    /// <summary>
    /// Gets the translated "BIRTHDATE" string.
    /// </summary>
    public string BIRTHDATE =>
LocalizationResourceManager.Instance.GetValue(nameof(BIRTHDATE));
    /// <summary>
    /// Gets the translated "WEIGHT" string.
    /// </summary>
    public string WEIGHT =>
LocalizationResourceManager.Instance.GetValue(nameof(WEIGHT));
    /// <summary>
    /// Gets the translated "UPDATE_CATEGORY" string.
    /// </summary>
    public string UPDATE_CATEGORY =>
LocalizationResourceManager.Instance.GetValue(nameof(UPDATE_CATEGORY));
    /// <summary>
    /// Gets the translated "YES" string.
    /// </summary>
    public string YES =>
LocalizationResourceManager.Instance.GetValue(nameof(YES));
    /// <summary>
    /// Gets the translated "NO" string.
    /// </summary>
    public string NO =>
LocalizationResourceManager.Instance.GetValue(nameof(NO));
    /// <summary>
    /// Gets the translated "CONFIRM_DELETE" string.
    /// </summary>
    public string CONFIRM_DELETE =>
LocalizationResourceManager.Instance.GetValue(nameof(CONFIRM_DELETE));
    /// <summary>
    /// Gets the translated "DELETE_CATEGORY_MESSAGE" string.
    /// </summary>
    public string DELETE_CATEGORY_MESSAGE =>
LocalizationResourceManager.Instance.GetValue(nameof(DELETE_CATEGORY_MESSAGE));
    /// <summary>
    /// Gets the translated "DELETE_COMPETITOR_MESSAGE" string.
    /// </summary>
    public string DELETE_COMPETITOR_MESSAGE =>
LocalizationResourceManager.Instance.GetValue(nameof(DELETE_COMPETITOR_MESSAGE));
    /// <summary>
    /// Gets the translated "DELETE_COMPETITION_MESSAGE" string.
    /// </summary>
    public string DELETE_COMPETITION_MESSAGE =>
LocalizationResourceManager.Instance.GetValue(nameof(DELETE_COMPETITION_MESSAGE));
    /// <summary>
    /// Gets the translated "DRAW" string.
    /// </summary>
    public string DRAW =>
LocalizationResourceManager.Instance.GetValue(nameof(DRAW));

    /// <summary>
    /// Initializes a new instance of the <see cref="ResourceProvider"/> class.
    /// Subscribes to the <see cref="LocalizationResourceManager"/>'s PropertyChanged event
    /// to refresh all bindings when the culture changes.
    /// </summary>
    public ResourceProvider()
    {
        LocalizationResourceManager.Instance.PropertyChanged += (sender, args) =>
        {
            OnPropertyChanged(null); // This will refresh all properties
        };
    }

    /// <summary>
    /// Raises the PropertyChanged event.
    /// </summary>
    /// <param name="propertyName">The name of the property that changed.</param>
    protected void OnPropertyChanged([CallerMemberName] string propertyName = "")
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
